apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    release: {{ .Release.Name }}
    app: mssql
  ports:
    - port: 1433
      nodePort: {{ .Values.nodePort }}
